PRAGMA foreign_keys=OFF;

DROP TABLE IF EXISTS "FanWorkVote";
DROP TABLE IF EXISTS "FanWorkVotePeriod";
DROP TABLE IF EXISTS "FanWork";
DROP TABLE IF EXISTS "Report";
DROP TABLE IF EXISTS "PostLike";
DROP TABLE IF EXISTS "Bookmark";
DROP TABLE IF EXISTS "PostTag";
DROP TABLE IF EXISTS "PostMedia";
DROP TABLE IF EXISTS "Comment";
DROP TABLE IF EXISTS "Post";
DROP TABLE IF EXISTS "Tag";
DROP TABLE IF EXISTS "Photo";
DROP TABLE IF EXISTS "Album";
DROP TABLE IF EXISTS "Event";

PRAGMA foreign_keys=ON;
